# Generated by Django 2.1.3 on 2018-11-07 09:16

from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=10)),
                ('correo', models.EmailField()),
                ('contrasena', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('region', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=30)),
                ('vivienda', models.CharField(max_length=30)),
            ],
        ),
    ]
